japan_facts = [
    "In Japanese, the name “Japan” is Nihon or Nippon, which means “Land of the Rising Sun.” It was once believed that Japan was the first country to see the sun rise in the East in the morning",
    "Japan has the third longest life expectancy in the world with men living to 81 years old and women living to almost 88 years old",
    "Japan consists of over 6,800 islands",
    "Home to 33 million people, the Tokyo-Yokohama metropolitan area is the largest populated metropolitan region in the world",
    "Japan has more than 3,000 McDonald’s restaurants, the largest number in any country outside the U.S",
    "69% of Japan is Covered in Forest",
    "70% of Japan is mountainous – including over 100 active volcanoes",
    "There are More than 1,500 Earthquakes a Year!",
    "The 1923 Kanto Earthquake was the Country’s Deadliest Earthquake",
    "Japan has the World’s Deepest Underwater Postbox",
    "Mount Fuji is a Sacred Place",
    "Japanese have a Deep Affection to Nature",
    "The Sea of Japan Holds an Abundance of Fish",
    "The Portuguese were the First Europeans to Visit Japan",
    "Japan had a Period of Complete Isolation from the Rest of the World",
    "Japanese Trains are Extremely Punctual",
    "The Oldest Onsen (Hot Spring) is 3,000 Years Old",
    "Only 1.7% of Land in Japan is Pastures and Grassland",
    "Only 12.7% of the Land in Japan is Okay for Agriculture",
    "Japan has one of the Lowest Unemployment Rates in the World",
    "Japan Just Legalized Gambling Casinos",
    "Japan Birth Rate is Lowest it’s Ever Been",
    "Slurping Noodles in Japan is a Sign of Appreciation",
    "Japan is one of the Safest Countries in the World",
    "In Japan there are no Shoes Allowed Inside",
    "There are Musical Toilets in Japan",
    "The Number 4 is Unlucky in Japan",
    "In Japan Black Cats are a Good Luck Charm",
    "Kids Get Taught How to Clean in School",
    "The Shortest Poetry in the World was Created in Japan and it is called Haiku",
    "Japan has Highest Number of Nobel Laureates In An Asian Country for Physics",
    "Japan is 3rd Biggest Producer of Cars in the World",
    "Japan has an Island of Rabbits (Okunoshima Island)",
    "The Shortest Escalator in the World (5 steps)",
    "Japan has the Busiest Train Station in the World (Shinjuku station 3.6 million people daily)",
    "The World’s First Novel Was Written Here (The Tale of Genji)",
    "Japan has been inhabited since 30,000 B.C.",
    "Japan imports 85% of Jamaica's annual coffee production",
    "Tokyo has the world's largest fish market, handling over 2000 tonnes of marine products daily.",
    "The traditional Christmas Eve meal is KFC",
    "In Japan there are ‘Maid Cafes’ where waitresses dressed in maid costumes act as servants, and treat customers as masters (and mistresses) in a private home, rather than as café patrons",
    "Animated Japanese films and television shows (i.e.: Anime) account for 60% of the world’s animation-based entertainment. So successful is animation in Japan, that there are almost 130 voice-acting schools in the country",
    "Around 24 billion pairs of chopsticks are used in Japan each year",
    "They use more paper for comics than for toilet paper in Japan",
    "Sometimes the trains in Japan are so crowded railway staff are employed to cram passengers inside",
    "Ovens are not nearly as commonplace as rice cookers in Japanese households",
    "There is almost no immigration in Japan. The population is 98% ethnic Japanese",
    "It’s considered inappropriate to blow your nose in public",
    "Japanese sake is made from fermented rice",
    "The fortune cookie dates back to the 19th century and was first made in Kyoto, Japan",
]